### ISSUE TITLE
uploading images to firebase

### ISSUE THREAD

**Issue by kulloveth** [kulloveth/WellnessCity#13]
this also requires getting the links to the images and fixing them in the right places in the json file

**Comment by JemimaNaomiBen** [comment]
I would try to work on this..But I'll need guidance

**Comment by kulloveth** [comment]
that's even the task I'm about embarking on, will create the firebase account and get back to you

**Comment by JemimaNaomiBen** [comment]
Okayyy.. Waiting

**Comment by kulloveth** [comment]
this is done now, you will grab the links from cloud storage and add to json file @JemimaNaomiBen
